services:
  reverse-proxy:
    image: traefik
    command:
      # Dashboard
      - --api.insecure=true
      - --api.dashboard=true

      # Providers
      - --providers.docker
      - --providers.docker.exposedbydefault=true

      # Entrypoints
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --entrypoints.web.http.redirections.entryPoint.scheme=https
      - --entrypoints.web.http.redirections.entrypoint.permanent=true

      # Let's Encrypt certificate resolver
      - --certificatesresolvers.jarnowiemannl-resolver.acme.tlschallenge=true
      - --certificatesresolvers.jarnowiemannl-resolver.acme.email=wiemanboy@gmail.com
      - --certificatesresolvers.jarnowiemannl-resolver.acme.storage=/letsencrypt/jarnowiemannl.json

      # Logs
      - --log.level=INFO
      - --log.filePath=/logs/traefik.log
      - --log.maxage=7
      - --accesslog=true
      - --accesslog.filepath=/logs/access.log
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - ./reverse-proxy-logs:/logs
      - ./letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock

  wiemansite:
    image: wiemanboy/wiemansite
    labels:
      - traefik.http.routers.WiemanSite.rule=Host(`jarnowieman.nl`)
      - traefik.http.routers.WiemanSite.entrypoints=websecure
      - traefik.http.routers.WiemanSite.tls.certresolver=jarnowiemannl-resolver

  blobstore:
    build:
        context: ./blobstore
        dockerfile: Dockerfile
    environment:
      MINIO_ROOT_USER: "username"
      MINIO_ROOT_PASSWORD: "password"
    ports:
      - "9001:9001"
    volumes:
      - ~/minio/data:/data
    command: server /data --console-address ":9001"
    labels:
      - traefik.http.routers.minio.rule=Host(`dev.jarnowieman.nl`)
      - traefik.http.services.minio.loadbalancer.server.port=9000
      - traefik.http.routers.minio.entrypoints=websecure
      - traefik.http.routers.minio.tls.certresolver=jarnowiemannl-resolver