version: '3.8'

services:
  reverse-proxy:
    image: traefik
    command:
      - --api.insecure=true
      - --providers.docker
      - --providers.docker.exposedbydefault=true
      - --entrypoints.web.address=:80
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  WiemanSite:
    image: wiemanboy/wiemansite
    labels:
      - traefik.http.routers.WiemanSite.rule=Host(`jarnowieman.duckdns.org`)
      - traefik.http.routers.WiemanSite.entrypoints=web

  minio:
    image: minio/minio:RELEASE.2024-06-13T22-53-53Z-cpuv1
    environment:
      MINIO_ROOT_USER: "username"
      MINIO_ROOT_PASSWORD: "password"
    volumes:
      - ~/minio/data:/data
    command: server /data --console-address ":9001"
    labels:
      - traefik.http.routers.minio.rule=Host(`jarnowieman.duckdns.org`) && Path(`/blobstore`)
      - traefik.http.services.minio.loadbalancer.server.port=9000
      - traefik.http.routers.minio.entrypoints=web
