global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'traefik'
    static_configs:
      - targets: ['reverse-proxy:8082']

  - job_name: 'node'
    static_configs:
      - targets: [ 'node-exporter:9100' ]