services:
  satisfactory:
    image: 'wolveix/satisfactory-server:latest'
    networks:
      - reverse_proxy_network
    ports:
      - '7777:7777/udp'
      - '7777:7777/tcp'
    volumes:
      - './data/satisfactory:/config'
    environment:
      - MAXPLAYERS=8
      - PGID=1000
      - PUID=1000
      - ROOTLESS=false
      - STEAMBETA=false
    deploy:
      resources:
        limits:
          memory: 16G
        reservations:
          memory: 4G
    labels:
      - traefik.enable=true
      - traefik.tcp.routers.satisfactory.rule=HostSNI(`dev.jarnowieman.nl`)
      - traefik.tcp.routers.satisfactory.entrypoints=websecure
      - traefik.tcp.routers.satisfactory.tls.certresolver=jarnowiemannl-resolver
      - traefik.tcp.routers.satisfactory.tls.passthrough=true
      - traefik.tcp.services.satisfactory.loadbalancer.server.port=7777

      - traefik.udp.routers.satisfactory.entrypoints=streaming
      - traefik.udp.services.satisfactory.loadbalancer.server.port=7777

networks:
  reverse_proxy_network:
    external: true