services:
  wiemansite:
    image: wiemanboy/wiemansite
    networks:
      - reverse_proxy_network
    environment:
      PUBLIC_API_BASE_URL: "https://jarnowieman.nl/api"
      PUBLIC_IMAGE_BASE_URL: "https://jarnowieman.nl/api/files"
    volumes:
      - ./data/wiemansite/images:/static/assets/images
    labels:
      - traefik.enable=true

      - traefik.http.routers.WiemanSiteJW.rule=Host(`jarnowieman.nl`) || Host(`www.jarnowieman.nl`)
      - traefik.http.routers.WiemanSiteJW.entrypoints=websecure
      - traefik.http.routers.WiemanSiteJW.tls.certresolver=jarnowiemannl-resolver

      - traefik.http.routers.WiemanSiteWB.rule=Host(`wiemanboy.com`) || Host(`www.wiemanboy.com`)
      - traefik.http.routers.WiemanSiteWB.entrypoints=websecure
      - traefik.http.routers.WiemanSiteWB.tls.certresolver=wiemanboycom-resolver


  file-browser:
      networks:
        - reverse_proxy_network
      image: hurlenko/filebrowser
      environment:
        FB_BASEURL: "/files"
      volumes:
        - ./data/wiemansite/images:/data
        - ./data/filebrowser/config:/config
      labels:
        - traefik.enable=true
        - traefik.http.routers.file-browser.rule=Host(`wiemanboy.com`) && PathPrefix(`/files`)
        - traefik.http.routers.file-browser.entrypoints=websecure
        - traefik.http.routers.file-browser.tls.certresolver=wiemanboycom-resolver
        - traefik.http.routers.file-browser.priority=100

networks:
  reverse_proxy_network:
    external: true
