services:
  minecraft:
    networks:
      - reverse_proxy_network
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    environment:
      EULA: "TRUE"
      MAX_MEMORY: "16G"
      TYPE: "VANILLA"
      VERSION: "SNAPSHOT"
      DIFFICULTY: "hard"
      ICON: "https://wiemanboy.com/favicon.svg"
      MAX_PLAYERS: "20"
      SNOOPER_ENABLED: "false"
      MAX_BUILD_HEIGHT: "256"
      SPAWN_PROTECTION: "0"
      VIEW_DISTANCE: "10"
      LEVEL: "world"
      ALLOW_FLIGHT: "TRUE"
      SERVER_NAME: "WiemanServer"
      PLAYER_IDLE_TIMEOUT: "0"
      EXEC_DIRECTLY: "true"
      ENABLE_WHITELIST: "true"
    volumes:
      - ./data/minecraft:/data
    deploy:
      resources:
        limits:
          memory: 16G
        reservations:
          memory: 4G
    ports:
      - "25565:25565"
    labels:
      - traefik.enable=true
      - traefik.tcp.routers.minecraft.rule=HostSNI(`*`)
      - traefik.tcp.routers.minecraft.entrypoints=minecraft

networks:
  reverse_proxy_network:
    external: true