services:
  minecraft:
    networks:
      - reverse_proxy_network
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    environment:
      EULA: "TRUE"
    volumes:
      - ./data/minecraft:/data
    deploy:
      resources:
        limits:
          memory: 16G
        reservations:
          memory: 4G
    labels:
      - traefik.enable=true
      - traefik.http.routers.minecraft.rule=Host(`mc.wiemanboy.com`)
      - traefik.http.routers.minecraft.entrypoints=websecure
      - traefik.http.services.minecraft.loadbalancer.server.port=25565
      - traefik.http.routers.minecraft.tls.certresolver=wiemanboycom-resolver

networks:
  reverse_proxy_network:
    external: true