services:
  reverse-proxy:
    image: traefik
    networks:
      - reverse_proxy_network
    secrets:
      - traefik_users
    command:
      # Dashboard
      - --api.dashboard=true

      # Providers
      - --providers.docker
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=reverse_proxy_network

      # Entrypoints
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443

      - --entryPoints.satisfactory-tcp.address=:7777
      - --entryPoints.satisfactory-udp.address=:7777/udp

      - --entryPoints.minecraft.address=:25565

      - --entryPoints.ark-client.address=:7778/udp
      - --entryPoints.ark-raw.address=:7778/udp
      - --entryPoints.ark-rcon.address=:27020/tcp
      - --entryPoints.ark-steam.address=:27015/udp

      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --entrypoints.web.http.redirections.entryPoint.scheme=https
      - --entrypoints.web.http.redirections.entrypoint.permanent=true
      - --serversTransport.insecureSkipVerify=true

      # Let's Encrypt certificate resolver
      - --certificatesresolvers.jarnowiemannl-resolver.acme.tlschallenge=true
      - --certificatesresolvers.jarnowiemannl-resolver.acme.email=wiemanboy@gmail.com
      - --certificatesresolvers.jarnowiemannl-resolver.acme.storage=/letsencrypt/jarnowiemannl.json

      - --certificatesresolvers.wiemanboycom-resolver.acme.tlschallenge=true
      - --certificatesresolvers.wiemanboycom-resolver.acme.email=wiemanboy@gmail.com
      - --certificatesresolvers.wiemanboycom-resolver.acme.storage=/letsencrypt/wiemanboycom.json

      # Logs
      - --log.level=INFO
      - --log.filePath=/logs/traefik.log
      - --log.maxage=7
      - --accesslog=true
      - --accesslog.filepath=/logs/access.log

      # Metrics
      - --metrics.prometheus=true
      - --metrics.prometheus.addEntryPointsLabels=true
      - --metrics.prometheus.addrouterslabels=true
      - --metrics.prometheus.addServicesLabels=true
      - --entryPoints.metrics.address=:8082
      - --metrics.prometheus.entryPoint=metrics
    labels:
      - traefik.enable=true
      - traefik.http.routers.dashboard.rule=Host(`network.wiemanboy.com`)
      - traefik.http.routers.dashboard.service=api@internal
      - traefik.http.routers.dashboard.middlewares=auth
      - traefik.http.routers.dashboard.entrypoints=websecure
      - traefik.http.routers.dashboard.tls.certresolver=wiemanboycom-resolver
      - traefik.http.middlewares.auth.basicauth.usersfile=/run/secrets/traefik_users
    ports:
      - "80:80"
      - "443:443"
      - "7777:7777"
      - "7777:7777/udp"
      - "8082:8082"
    volumes:
      - ./data/logs/reverse-proxy:/logs
      - ./data/letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock

  node-exporter:
    networks:
      - logging_network
    image: prom/node-exporter

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    networks:
      - logging_network
    ports:
      - ":8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro

  prometheus:
    image: prom/prometheus
    networks:
      - reverse_proxy_network
      - logging_network
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./data/logs/prometheus:/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.retention.size=10GB
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    networks:
      - reverse_proxy_network
      - logging_network
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    labels:
      - traefik.enable=true
      - traefik.http.routers.grafana.rule=Host(`dashboard.wiemanboy.com`)
      - traefik.http.routers.grafana.entrypoints=websecure
      - traefik.http.routers.grafana.tls.certresolver=wiemanboycom-resolver
    volumes:
      - ./data/grafana/storage:/var/lib/grafana

networks:
  reverse_proxy_network:
    external: true
  logging_network:

secrets:
  traefik_users:
    external: true