services:
  minecraft:
    networks:
      - reverse_proxy_network
      - minecraft_network
    image: itzg/minecraft-server:latest
    tty: true
    stdin_open: true
    environment:
      EULA: "TRUE"
      MAX_MEMORY: "16G"
      TYPE: "AUTO_CURSEFORGE"
      VERSION: "1.20.1"
      DIFFICULTY: "hard"
      ICON: "https://wiemanboy.com/assets/images/JW_LOGO"
      MOTD: "§l§5WiemanServer§r\n§rWelcome to my server!"
      CF_PAGE_URL: "https://www.curseforge.com/minecraft/modpacks/beyond-depth/files/6804979"
      CF_API_KEY: %%CF_API_KEY%% 
      #/run/secrets/cf_api_key
      CURSEFORGE_FILES: |
        https://www.curseforge.com/minecraft/mc-mods/bluemap/files/5555753
      MAX_PLAYERS: "20"
      SNOOPER_ENABLED: "false"
      MAX_BUILD_HEIGHT: "256"
      SPAWN_PROTECTION: "0"
      VIEW_DISTANCE: "8"
      LEVEL: "beyond-depth"
      ALLOW_FLIGHT: "TRUE"
      SERVER_NAME: "WiemanServer"
      PLAYER_IDLE_TIMEOUT: "0"
      EXEC_DIRECTLY: "true"
      ENABLE_WHITELIST: "true"
      ONLINE_MODE: "false"
    volumes:
      - ./data/minecraft:/data
    ports:
      - ":25565"
      - ":8123"
    deploy:
      resources:
        limits:
          memory: 16G
        reservations:
          memory: 4G
    labels:
      - traefik.enable=true

      - traefik.tcp.routers.minecraft.rule=HostSNI(`*`)
      - traefik.tcp.routers.minecraft.entrypoints=minecraft

      - traefik.http.routers.mcmap.service=mcmap-service
      - traefik.http.services.mcmap-service.loadbalancer.server.port=8123
      - traefik.http.routers.mcmap.rule=Host(`mc.wiemanboy.com`)
      - traefik.http.routers.mcmap.entrypoints=websecure
      - traefik.http.routers.mcmap.tls.certresolver=wiemanboycom-resolver
    #secrets:
    #  - cf_api_key

  minecraft-backups:
    networks:
      - minecraft_network
    image: itzg/mc-backup
    environment:
      BACKUP_INTERVAL: "2h"
      RCON_HOST: "minecraft"
      RCON_PORT: "25575"
      BACKUP_NAME: "beyond-depth"
      PRUNE_BACKUPS_DAYS: "7"
      PAUSE_IF_NO_PLAYERS: "true"
      PRE_BACKUP_SCRIPT: |
        rcon-cli say "§l§d$$(TZ="Europe/Amsterdam" date +"[%Y/%m/%d %H:%M:%S]")§r §eStarting backup..."
      POST_BACKUP_SCRIPT: |
        rcon-cli say "§l§d$$(TZ="Europe/Amsterdam" date +"[%Y/%m/%d %H:%M:%S]")§r §eBackup complete -> §c$$(ls -1 *.tgz | tail -n 1 | sed 's/\.tgz$$//')§r§e, next backup at: §a§u$$(TZ="Europe/Amsterdam" date -d "$$(echo $$BACKUP_INTERVAL | sed 's/h$$//') hours" +"%H:%M")"
      POST_BACKUP_SCRIPT_FILE: /post-backup.sh
    volumes:
      - ./data/minecraft:/data:ro
      - ./data/minecraft-backups:/backups

networks:
  reverse_proxy_network:
    external: true
  minecraft_network:

#secrets:
#  cf_api_key:
#    file: cf_api_key.secret