services:
  minecraft:
    networks:
      - reverse_proxy_network
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    environment:
      EULA: "TRUE"
    volumes:
      - ./data/minecraft:/data
    deploy:
      resources:
        limits:
          memory: 16G
        reservations:
          memory: 4G
    labels:
      - traefik.enable=true
      - traefik.tcp.routers.minecraft.rule=HostSNI(`*`)
      - traefik.tcp.routers.minecraft.entrypoints=minecraft

networks:
  reverse_proxy_network:
    external: true