services:
  minecraft:
    networks:
      - reverse_proxy_network
      - minecraft_network
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    environment:
      EULA: "TRUE"
      MAX_MEMORY: "16G"
      TYPE: "VANILLA"
      VERSION: "SNAPSHOT"
      DIFFICULTY: "hard"
      ICON: "https://jarnowieman.nl/api/files/minecraft/server_icon"
      MOTD: "Welcome to the WiemanServer"
      MAX_PLAYERS: "20"
      SNOOPER_ENABLED: "false"
      MAX_BUILD_HEIGHT: "256"
      SPAWN_PROTECTION: "0"
      VIEW_DISTANCE: "10"
      LEVEL: "world"
      ALLOW_FLIGHT: "TRUE"
      SERVER_NAME: "WiemanServer"
      PLAYER_IDLE_TIMEOUT: "0"
      EXEC_DIRECTLY: "true"
      ENABLE_WHITELIST: "true"
    volumes:
      - ./data/minecraft:/data
    ports:
      - "25565:25565"
    deploy:
      resources:
        limits:
          memory: 16G
        reservations:
          memory: 4G
    labels:
      - traefik.enable=true
      - traefik.tcp.routers.minecraft.rule=HostSNI(`*`)
      - traefik.tcp.routers.minecraft.entrypoints=minecraft

  minecraft-backups:
    networks:
      - minecraft_network
    image: itzg/mc-backup
    environment:
      BACKUP_INTERVAL: "2h"
      RCON_HOST: "minecraft"
      RCON_PORT: "25575"
      BACKUP_NAME: "world"
      PRUNE_BACKUPS_DAYS: "7"
      PAUSE_IF_NO_PLAYERS: "true"
      PRE_BACKUP_SCRIPT: |
        echo "Starting backup from $$RCON_HOST to $$DEST_DIR"
      POST_BACKUP_SCRIPT: |
        echo "Backup complete"
      POST_BACKUP_SCRIPT_FILE: /post-backup.sh
    volumes:
      - ./data/minecraft:/data:ro
      - ./data/minecraft-backups:/backups

networks:
  reverse_proxy_network:
    external: true
  minecraft_network:
    external: true