services:
  server:
    image: hermsi/ark-server:latest
    networks:
      - reverse_proxy_network
      - ark_network
    volumes:
      - ./data/ark/server:/app
      - ./data/ark/backups:/home/steam/ARK-Backups
    environment:
      SESSION_NAME: WiemanServer
      SERVER_MAP: TheIsland
      MAX_PLAYERS: 10
      BACKUP_ON_STOP: "true"
      DISABLE_BATTLEYE: "true"
      GAME_CLIENT_PORT: 7778
      UDP_SOCKET_PORT: 7779
      GAME_MOD_IDS:
    deploy:
      resources:
        limits:
          memory: 16G
        reservations:
          memory: 4G
    labels:
      - traefik.enable=true
      - traefik.http.routers.ark.rule=Host(`ark.wiemanboy.com`)
      - traefik.http.routers.ark.entrypoints=ark-rcon
      - traefik.http.services.ark.loadbalancer.server.scheme=https
      - traefik.http.routers.ark.tls.certresolver=wiemanboycom-resolver

      - traefik.udp.routers.ark.entrypoints=ark-client ark-raw ark-steam

networks:
  reverse_proxy_network:
    external: true
  ark_network: