services:
  ark:
    image: wiemanboy/ark-server:latest
    networks:
      - reverse_proxy_network
      - ark_network
    volumes:
      - ./data/ark/server:/app
      - ./data/ark/backups:/home/steam/ARK-Backups
    environment:
      SESSION_NAME: WiemanServer
      SERVER_MAP: Fjordur
      MAX_PLAYERS: 10
      BACKUP_ON_STOP: "true"
      DISABLE_BATTLEYE: "true"
      GAME_CLIENT_PORT: 7778
      UDP_SOCKET_PORT: 7779
      GAME_MOD_IDS: "839162288,1315573129,902157012,899987403,731604991,812639416,764792033,821530042,786896932,693416678,1837445660,754885087,2594067220,761535755,2200048898"
    deploy:
      resources:
        limits:
          memory: 16G
        reservations:
          memory: 4G
    ports:
      - "7778:7778/udp"
      - "7779:7779/udp"
      - "27020:27020/tcp"
      - "27015:27015/udp"
    labels:
      - traefik.enable=true
      #- traefik.http.routers.ark.rule=Host(`ark.wiemanboy.com`)
      #- traefik.http.routers.ark.entrypoints=ark-rcon
      #- traefik.http.services.ark.loadbalancer.server.scheme=https
      #- traefik.http.routers.ark.tls.certresolver=wiemanboycom-resolver

      #- traefik.udp.routers.ark.service=ark-service
      #- traefik.udp.services.ark-service.loadbalancer.server.port=7778
      #- traefik.udp.routers.ark.entrypoints=ark-client,ark-raw,ark-steam

networks:
  reverse_proxy_network:
    external: true
  ark_network: