services:
  minecraft:
    networks:
      - reverse_proxy_network
      - minecraft_network
    image: itzg/minecraft-server:latest
    tty: true
    stdin_open: true
    environment:
      EULA: "TRUE"
      MAX_MEMORY: "16G"
      TYPE: "AUTO_CURSEFORGE"
      VERSION: "1.21.1"
      DIFFICULTY: "hard"
      ICON: "https://jarnowieman.nl/api/files/minecraft/server_icon"
      MOTD: "§l§5WiemanServer§r\n§rWelcome to my server!"
      VANILLATWEAKS_SHARECODE: "cFTVFy,M6j9tu"
      DATAPACKS: ""
      CF_PAGE_URL: "https://www.curseforge.com/minecraft/modpacks/all-the-mods-10/files/6091559"
      CF_API_KEY: %%CF_API_KEY%%
      CURSEFORGE_FILES: |
        https://www.curseforge.com/minecraft/mc-mods/bluemap/files/5919132
      #  https://www.curseforge.com/minecraft/bukkit-plugins/dynmap/files/6090792 # PAPERMC dynmap
      MAX_PLAYERS: "20"
      SNOOPER_ENABLED: "false"
      MAX_BUILD_HEIGHT: "256"
      SPAWN_PROTECTION: "0"
      VIEW_DISTANCE: "10"
      LEVEL: "atm10"
      ALLOW_FLIGHT: "TRUE"
      SERVER_NAME: "WiemanServer"
      PLAYER_IDLE_TIMEOUT: "0"
      EXEC_DIRECTLY: "true"
      ENABLE_WHITELIST: "true"
    volumes:
      - ./data/minecraft:/data
    ports:
      - "25565:25565"
      - "8123:8123"
    deploy:
      resources:
        limits:
          memory: 16G
        reservations:
          memory: 4G
    labels:
      - traefik.enable=true

      - traefik.tcp.routers.minecraft.rule=HostSNI(`*`)
      - traefik.tcp.routers.minecraft.entrypoints=minecraft

      - traefik.http.routers.mcmap.service=mcmap-service
      - traefik.http.services.mcmap-service.loadbalancer.server.port=8123
      - traefik.http.routers.mcmap.rule=Host(`mc.wiemanboy.com`)
      - traefik.http.routers.mcmap.entrypoints=websecure
      - traefik.http.routers.mcmap.tls.certresolver=wiemanboycom-resolver

  minecraft-backups:
    networks:
      - minecraft_network
    image: itzg/mc-backup
    environment:
      BACKUP_INTERVAL: "2h"
      RCON_HOST: "minecraft"
      RCON_PORT: "25575"
      BACKUP_NAME: "world"
      PRUNE_BACKUPS_DAYS: "7"
      PAUSE_IF_NO_PLAYERS: "true"
      PRE_BACKUP_SCRIPT: |
        rcon-cli say "§l§d$$(TZ="Europe/Amsterdam" date +"[%Y/%m/%d %H:%M:%S]")§r §eStarting backup..."
      POST_BACKUP_SCRIPT: |
        rcon-cli say "§l§d$$(TZ="Europe/Amsterdam" date +"[%Y/%m/%d %H:%M:%S]")§r §eBackup complete -> §c$$(ls -1 *.tgz | tail -n 1 | sed 's/\.tgz$$//')§r§e, next backup at: §a§u$$(TZ="Europe/Amsterdam" date -d "$$(echo $$BACKUP_INTERVAL | sed 's/h$$//') hours" +"%H:%M")"
      POST_BACKUP_SCRIPT_FILE: /post-backup.sh
    volumes:
      - ./data/minecraft:/data:ro
      - ./data/minecraft-backups:/backups

networks:
  reverse_proxy_network:
    external: true
  minecraft_network: