name: Deploy
on:
  push:
    branches:
      - master
      - release/**

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: multiple command
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            rsync -avz --exclude 'data' ./ ~/server
            cd ~/server
            make deploy